pequeñas modificaciones y facs añadidos para prohd0016.xml
humboldtdigital/ediciones pull request #13
Opened 2021-12-02 10:38 UTC by trafikante

Es lo que he hecho o quisiera comentar:

- El abstract requiere una revisión por parte de Alaina y Grisel (Email TK a todos, 02.12.21). 
- Incluí los valores de `@facs` en `<pb/>` a base del nuevo escaneo de la OHC (Nov 21) que mandó Alaina. 
-- Para ello, transformé las dos páginas del PDF original en TIFF y en PTIF (pyramidal tiff)
-- no sé si lo he hecho bien, pero usé una herramienta en línea, [Vertopal](https://www.vertopal.com/en/picture/convert/tif-to-ptif)
-- los archivos tif y ptif se encuentran en Nextcloud\CENTRO_ProHD\Korpus\Quellen\OHCH\Consulta a gobernador (Ana del Toro)\2021-11-11 nuevo scan
-- en el código, usé los TIFs regulares a base de una enumeración con cuatro digitos
El resto son cambios más bien pequeños.

2021-12-02 13:14 UTC, arojascastro commented on prohd0016.xml
> +            <pb n="1" facs="0001.xml"/>
esto es 0001.tif no?

2021-12-02 13:14 UTC, arojascastro commented on prohd0016.xml
> -                        <category xml:id="print"/>
esto no hace falta borrarlo

2021-12-02 13:15 UTC, arojascastro commented on prohd0016.xml
> -                        <category xml:id="climatology"/>
las categorías de aquí no hace falta borrarlas; ea la taxonomía; no significa que se esté categorizando el documento sino las opciones posibles...

2021-12-02 13:16 UTC, arojascastro requested changes
Hola Tobias, 

Tengo algunas dudas sobre algunos cambios. 

Puedes mirar mis comentarios? 

Gracias

2021-12-02 13:17 UTC, arojascastro commented on prohd0016.xml
> -                        <category xml:id="climatology"/>
lo mismo con el resto de categorías; que formen parte de la taxonomía no significa que se hayan usado

2021-12-03 08:31 UTC, trafikante commented on prohd0016.xml
> +            <pb n="1" facs="0001.xml"/>
si, perdón, error mío.

2021-12-03 08:33 UTC, trafikante commented on prohd0016.xml
> -                        <category xml:id="print"/>
ok, muy bien, no sabía eso. Pero como distinguimos entonces en el código entre categorias posibles y las que se eligieron para el documento?

2021-12-03 08:33 UTC, trafikante commented on prohd0016.xml
> -                        <category xml:id="climatology"/>
see above

2021-12-07 07:31 UTC, arojascastro commented on prohd0016.xml
> -                        <category xml:id="print"/>
Las categoría usadas se codifican en *textClass*. Por ejemplo: 

```
<textClass>
                <catRef scheme="#genre" target="#correspondence"/>
                <catRef scheme="#form" target="#manuscript"/>
            </textClass>
```

Son dos lugares y etiquetas distintas: por un lado, *textClass*; por el otro, *taxonomy*

2021-12-07 13:13 UTC, trafikante commented on prohd0016.xml
> -                        <category xml:id="print"/>
Entendido, gracias. Eso me hace recordar que justo en este documento discutimos la posibilidad de incluir otra categoría en `<category xml:id="subjects">` para referirse a actos de la administración/política colonial.

Se te ocurre un término que podriamos adaptar de las normas españolas?

2022-01-11 09:19 UTC, arojascastro approved these changes

2022-01-11 09:19 UTC, merged